force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/deptno__c.field-meta.xml
<CustomField>
    <fullName>deptno__c</fullName>
    <label>deptno</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>ename</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpsertClass.cls
@isTest
public class UpsertClass {
    public static testmethod void main(){
        List<employee__c> obj = new List<employee__c>();
        	
        obj = [select salary__c from employee__c];
        
        for(Employee__C er : obj) 
            er.salary__c += 10000;
        
        Employee__c obj1 = new Employee__c();
        obj1.ename__c = 'AMAN';
        obj1.salary__c = 10234;
        obj1.deptno__c = '10';
        
        obj.add(obj1);
        
        upsert obj;
            
    }
}