force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BeyondGL.cls
public class BeyondGL implements database.Batchable<employee__c> , database.stateful{
    string name = 'Kanishk';
	//1) start
    public Iterable<employee__c> start(database.BatchableContext bc){
        system.debug('i am in start method ' + name);
        name = 'Guroor';
        return [select salary__c from employee__c];
    }
    
    //2) execute
    public void execute(database.BatchableContext bc, List<employee__c> obj){
        system.debug('i am in start method ' + name);
        name = 'ketan';
        for(employee__c  er : obj)
            er.salary__c += 11000;
        update obj;
    }
    
    //3) finish
    public void finish(database.BatchableContext bc){
        system.debug('i am in start method ' + name);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        String[] toAddress = new String[]{'jatinpawar1920@gmail.com' , 'pawarjatinlakshay2000@gmail.com'};
        
        mail.setToAddresses(toAddress);
        mail.setSubject('Batch Apex Job Completed');
        mail.setplainTextBody('The batch job that you are started that is completed');
        messaging.sendEmail(new messaging.SingleEmailMessage[]{mail});
    }
    
}