force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/deptno__c.field-meta.xml
<CustomField>
    <fullName>deptno__c</fullName>
    <label>deptno</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>ename</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <label>job</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/insert_cc_Class.cls
public class insert_cc_Class {

    public String deptno { get; set; }

    public String job { get; set; }

    public integer salary { get; set; }

    public String ename { get; set; }

    public PageReference cancel() {
        return null;
    }


    public PageReference insertfun() {
        employee__c obj = new employee__c();
        obj.ename__c = ename;
        obj.salary__c = salary;
        obj.deptno__c = deptno;
        obj.job__c = job;
        insert obj;
        
        PageReference pr = new PageReference('https://herofincorp13-dev-ed.develop.my.salesforce.com/a03/o');
        return pr;
    }

}