force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchApex.cls
public class BatchApex implements database.Batchable<employee__c>{
	//1) start
    public Iterable<employee__c> start(database.BatchableContext bc){
        return [select salary__c from employee__c];
    }
    
    //2) execute
    public void execute(database.BatchableContext bc, List<employee__c> obj){
        for(employee__c  er : obj)
            er.salary__c += 11000;
        update obj;
    }
    
    //3) finish
    public void finish(database.BatchableContext bc){
        
    }
}