force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/deptno__c.field-meta.xml
<CustomField>
    <fullName>deptno__c</fullName>
    <label>deptno</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>ename</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/fields/salary__c.field-meta.xml
<CustomField>
    <fullName>salary__c</fullName>
    <label>salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/classTestClass4.cls
@isTest
public class classTestClass4 {
    public static testmethod void main(){
        List<employee__c> obj = new List<employee__c>();
        obj = [select name, ename__c, deptno__c, salary__c from employee__c where deptno__c like '10' limit 5];
        integer count = 0;
        for(employee__c er : obj){
            system.debug('Student ' + count++ + ' DETAISL : ' + er);
        }
        
    }
}