force-app/main/default/objects/my_custom_metadata__mdt/my_custom_metadata__mdt.object-meta.xml
<CustomObject>
    <label>my custom metadata</label>
    <pluralLabel>my custom metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/my_custom_metadata__mdt/fields/flag__c.field-meta.xml
<CustomField>
    <fullName>flag__c</fullName>
    <defaultValue>true</defaultValue>
    <label>flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomMetadataDemo.cls
public class CustomMetadataDemo {
    public void getCustomMetadataDetails(){
        	my_custom_metadata__mdt mdata = 	my_custom_metadata__mdt.getInstance('my_metadt');
        	system.debug(mdata);
        	system.debug('value of flag in custom metadata is ' + mdata.flag__c);
        
        	if(mdata.flag__c == true)
           		system.debug('Please Execute...');
            else 
                system.debug('Please Dont Execute...');
        	
    }
}