force-app/main/default/objects/HeroEmployee__c/HeroEmployee__c.object-meta.xml
<CustomObject>
    <label>HeroEmployee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HeroEmployees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HeroEmployee__c/fields/employee_address__c.field-meta.xml
<CustomField>
    <fullName>employee_address__c</fullName>
    <label>employee address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HeroEmployee__c/fields/employee_dept_name__c.field-meta.xml
<CustomField>
    <fullName>employee_dept_name__c</fullName>
    <label>employee dept name</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HeroEmployee__c/fields/employee_father_s_name__c.field-meta.xml
<CustomField>
    <fullName>employee_father_s_name__c</fullName>
    <label>employee father&apos;s name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HeroEmployee__c/fields/employee_name__c.field-meta.xml
<CustomField>
    <fullName>employee_name__c</fullName>
    <label>employee_name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HeroEmployee__c/fields/employee_salary__c.field-meta.xml
<CustomField>
    <fullName>employee_salary__c</fullName>
    <label>employee salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HeroEmployeeClass.cls
public class HeroEmployeeClass {
	@auraEnabled
    public static void insertEmployee(string ename,string efname,string eadd, string edept, string esal){
        HeroEmployee__c hemp = new  HeroEmployee__c();
        hemp.employee_name__c = ename;
        hemp.employee_father_s_name__c = efname;
        hemp.employee_address__c = eadd;
        hemp.employee_dept_name__c = edept;
        hemp.employee_salary__c = Integer.valueof(esal);
        insert hemp;
    }
}